# 2017 May 26
# https://docpad.org/docs/deploy
# https://github.com/balupton/awesome-travis
sudo: false
language: node_js
node_js:
  - "7"     # stable
cache:
  directories:
    - $HOME/.npm  # npm's cache
    - $HOME/.yarn-cache  # yarn's cache
before_script:
  - eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/deploy-custom.bash)"
notifications:
  email:
    recipients:
      secure: Z4KR9AamZhchSbm31DBGRhy2zTnhD7ULxCqgCYSHXlCNzf86HfWSelJsuaUKW/XaQZyn8xwRX9Dc+5FAc0F6eQgdEL01XRC6PAlZ9cUVPJ/YixxNWXArdyOjug53+3a+f/H6qRfuySaPnSkZ0KgCgb01A3mElTl0/0shuFPvXzI=
  slack:
    secure: FT6SHO7c/O9gbaiMLRPDEncNTi41BAw3WFcbipCwBHB/Y1sehh8WTth9nqWhiEIED6ekZDN9fZy7SNSwRsg/KJxdf0ma4Zc/2zVvXIUdpxGxibfDEULiSFBCHL1FBpNFcP+lukUs+0Pb0p1HegzRfrbu1mioXfrXvzTpprn4lQw=
